/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Idea } from "./Idea";
import { IdeaCountArgs } from "./IdeaCountArgs";
import { IdeaFindManyArgs } from "./IdeaFindManyArgs";
import { IdeaFindUniqueArgs } from "./IdeaFindUniqueArgs";
import { CreateIdeaArgs } from "./CreateIdeaArgs";
import { UpdateIdeaArgs } from "./UpdateIdeaArgs";
import { DeleteIdeaArgs } from "./DeleteIdeaArgs";
import { CommentFindManyArgs } from "../../comment/base/CommentFindManyArgs";
import { Comment } from "../../comment/base/Comment";
import { VoteFindManyArgs } from "../../vote/base/VoteFindManyArgs";
import { Vote } from "../../vote/base/Vote";
import { User } from "../../user/base/User";
import { IdeaService } from "../idea.service";
@graphql.Resolver(() => Idea)
export class IdeaResolverBase {
  constructor(protected readonly service: IdeaService) {}

  async _ideasMeta(
    @graphql.Args() args: IdeaCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Idea])
  async ideas(@graphql.Args() args: IdeaFindManyArgs): Promise<Idea[]> {
    return this.service.ideas(args);
  }

  @graphql.Query(() => Idea, { nullable: true })
  async idea(@graphql.Args() args: IdeaFindUniqueArgs): Promise<Idea | null> {
    const result = await this.service.idea(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Idea)
  async createIdea(@graphql.Args() args: CreateIdeaArgs): Promise<Idea> {
    return await this.service.createIdea({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Idea)
  async updateIdea(@graphql.Args() args: UpdateIdeaArgs): Promise<Idea | null> {
    try {
      return await this.service.updateIdea({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Idea)
  async deleteIdea(@graphql.Args() args: DeleteIdeaArgs): Promise<Idea | null> {
    try {
      return await this.service.deleteIdea(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Comment], { name: "comments" })
  async findComments(
    @graphql.Parent() parent: Idea,
    @graphql.Args() args: CommentFindManyArgs
  ): Promise<Comment[]> {
    const results = await this.service.findComments(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Vote], { name: "votes" })
  async findVotes(
    @graphql.Parent() parent: Idea,
    @graphql.Args() args: VoteFindManyArgs
  ): Promise<Vote[]> {
    const results = await this.service.findVotes(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  async getUser(@graphql.Parent() parent: Idea): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
